
- id: qmlformat
  name: qmlformat
  description: Check and format QML files using qmlformat.
  entry: qmlformat-hook
  language: python
  files: '.*\.qml$'
  additional_dependencies:
  - PySide6-Essentials
